sudo: required
language: python
services:
- docker
env:
  global:
  - DOCKER_REPO=webapp-images
  - EB_REGION="eu-west-1"
before_install:
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- cd ./src/VW.SPA
- docker build -t $DOCKER_REPO .
- cd ../.. 
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
  on:
    branch: development