sudo: required
language: python
services:
- docker
# safelist
branches:
  only:
  - master
  - staging
  - development
before_install:
- pip install awscli
- export PATH=$PATH:$HOME/.local/bin
script:
- cd ./src/VW.SPA
- docker build -t $DOCKER_REPO .
- cd ../..
- bash docker_push.sh
deploy:
  - provider: script
    script: bash elasticbeanstalk_deploy.sh
    skip_cleanup: true
    on:
        branch: development
  - provider: script
    script: bash elasticbeanstalk_deploy.sh
    skip_cleanup: true
    on:
        branch: staging
  - provider: script
    script: bash elasticbeanstalk_deploy.sh
    skip_cleanup: true
    on:
        branch: master